### ISSUE TITLE
fzf or Telescope support

### ISSUE THREAD

**Issue by Arrow-x** [hugginsio/twig.nvim#2]
This is a great Idea, but it will be so use full to pipe the results to `fzf` or `Telescope`, maybe add custom keybind to create, delete, start, finish tasks

**Comment by Arrow-x** [comment]
this is perhaps beyond the scope of this plugin since https://github.com/ribelo/taskwarrior.nvim exist

**Comment by hugginsio** [comment]
Hello Arrow-x - thanks for your interest in twig!

I agree with your assessment. Recreating vit, taskwarrior-tui, or more advanced existing Taskwarrior plugins is outside the scope of what I originally intended for this plugin.

However, I am still trying out different ways to interact with Taskwarrior (including the plugin you linked) and I am interested in adding some behavior similar to what you mentioned. Right now I envision a command that opens a floating temporary terminal window that opens taskwarrior-tui with the current buffer's project so that I can quickly edit the task list for that project.
